### ISSUE TITLE
Shifted sticky view on Android

### ISSUE THREAD

**Issue by dhavrosh** [shimohq/react-native-keyboard-view#23]
Hey guys,

I'd like to use your module, on iOS everything is good, but on Android sticky view is shifted up almost on half of a screen. Does somebody know how to fix it?

**Comment by magicismight** [comment]
Did you use a TextInput in the sticky view?
I had faced the same problem before.
You can fix this by doing this:

```
renderStickyView() {
  return (
    <View style={{top: -100,transform:[{translateY:100}]}}></View>
  );
}
```

**Comment by magicismight** [comment]
If the TextInput is covered by the keyboard, the system will shift the whole activity to avoid the keyboard.
Make the StickyView's layout is never covered by the keyboard and translate it into the right place.

**Comment by dhavrosh** [comment]
@magicismight I've tried your solution, but it again worked as described above,
nevertheless thanks for your advice. For now I've set `windowSoftInputMode="adjustPan"` and it works as expected
