### ISSUE TITLE
Open a keyboard by input inside a sticky view

### ISSUE THREAD

**Issue by dhavrosh** [shimohq/react-native-keyboard-view#24]
Hey guys,

I'd like to ask you if here is a way to open a keyboard by calling an input from a sticky view.
I've tried to something like that :

```
class Keyboard extends Component {

render() {
    return (
        <View style={styles.container}>
          <KeyboardView
              ref='keyboard'
              onShow={this.onShow}
              renderStickyView={this.renderStickyView}>
          </KeyboardView>
          <TextInput ref='_input' style={styles.hiddenInput}/>
        </View>
    );
  }

@autobind
  renderStickyView() {
    const Input = this.props.input;

    return <Input ref='input' />;
  }

@autobind
open() {
    // this.refs._input.focus();
    this.refs.keyboard.refs.input.focus();
  }
}
```

Regardless keyboard has a ref 'input' and I can access to all it's methods, it doesn't work (when I call `this.refs.keyboard.refs.input.focus()` from my open method).
When I try to call `this.refs._input.focus()` and inside onShow method change inputs focus by `this.refs.keyboard.refs.input.focus()` it works. 

I need a proper solution without calling another input.

**Comment by magicismight** [comment]
Fixed in 2.0.0-rc8.
