### ISSUE TITLE
android Show wrong

### ISSUE THREAD

**Issue by lixiaozhangme** [shimohq/react-native-keyboard-view#41]
![b7dbe82b-b33c-491e-b44b-666b99f9f2d3](https://user-images.githubusercontent.com/19645470/32591728-34d1e322-c4e6-11e7-8643-6e44c70cdf67.png)

**Comment by magicismight** [comment]
Plz make sure you have set  `android:windowSoftInputMode="adjustPan"` in `AndroidManifest.xml`
